http:
  #最大连接数
  maxTotal: 5000
  #并发数
  defaultMaxPerRoute: 3000
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 15000
spring:
  #redis客户端超时时间
  redisTimeout: 10000
  lettuce:
    #关闭超时连接时间
    shutdown-timeout: 100
    pool:
      #连接池最大连接数
      max-active: 8
      #连接池最小空闲连接数（-1为没有限制）
      min-idle: -1
      #最大建立连接等待时间，超过将报出异常
      max-wait: 2000
  redis1:
    host: 127.0.0.1
    port: 6379
  redis2:
    host: 47.100.235.4
    port: 6379
    password: codis123456

swagger:
  show: true

image:
  url: image/